version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: face-attendance-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-service:
    build:
      context: ./ml-service
    container_name: face-attendance-ml
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DISTANCE_THRESHOLD=0.48

volumes:
  mongo_data:
